# Generated by Django 2.0.13 on 2019-06-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0002_auto_20190628_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_details',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
