# Generated by Django 2.0.13 on 2019-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0005_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
