# Generated by Django 2.0.13 on 2019-06-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0006_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='eDate',
            field=models.DateField(),
        ),
    ]
